version: '3.9'
services:

  adminer-mariadb:
    restart: unless-stopped
    build:
      context: ./library
      dockerfile: adminer.dockerfile
    image: ${APP_CONTAINER_NAME}_adminer:adminer
    container_name: ${APP_CONTAINER_NAME}_adminer_mariadb
    networks:
        - ${APP_NETWORK}
    ports:
        - 9012:8080
    environment:
        # ADMINER_DB: adminer
        ADMINER_DRIVER: server
        ADMINER_SERVER: mariadb
        ADMINER_USERNAME: root
        ADMINER_PASSWORD: password
        ADMINER_AUTOLOGIN: 1
        ADMINER_NAME: MariaDB

  # Database
  mariadb:
    restart: unless-stopped
    image: mariadb:10.5.9
    container_name: ${APP_CONTAINER_NAME}_mariadb
    environment:
      # MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'pauli'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3307:3306
    volumes:
      - ${APP_WORK_DATA}:/projects:delegated
      - ./backups:/backups
      # - database-volume:/var/lib/mysql
    networks:
      - ${APP_NETWORK}
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=${MYSQL_ROOT_PASS} 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }

networks:
  workspace:
    name: ${APP_NETWORK}
