version: '3.9'
services:

  test-php:
    restart: unless-stopped
    build:
      args:
        user: ${DOCKER_USER}
        uid: ${DOCKER_UID}
      context: ./library
      dockerfile: test.php.dockerfile
    image: ${APP_CONTAINER_NAME}_test_php:test_php
    container_name: ${APP_CONTAINER_NAME}_test_php
    volumes:
      - ${APP_WORK_DATA}:/projects:delegated
      - ${APP_DATA}:/docker:delegated
    working_dir: /projects
    networks:
      - ${APP_NETWORK}

networks:
  workspace:
    name: ${APP_NETWORK}
